name: "jnvc583.github.io"
description: "Code provider"
avatar: https://jnvc583.github.io/images/avatar.png
footer-links:
  zhihu:
  email: jnvcotc@zohomail.cn
  github: jnvc583
  rss: # just type anything here for a working RSS icon
  twitter:
  youtube:
footer-text: Copyright (c) 2020 JNVCOTC

url: https://jnvc583.github.io

permalink: ./404.html
